version: "3"
services:
  api-database:
    image: postgres
    container_name: "api-database"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "root"
  api:
    image: devnato/api-fin-basic:0.0.1
    container_name: "api"
    ports:
      - 8080:8080
    links:
      - api-database:app_db